name: copilot-deploy-backend

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read

jobs:
  web-api:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: "Install SWA CLI"
        run: npm install -g @azure/static-web-apps-cli

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false

      - name: frontend
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            webappName=$(az deployment group show --name ${{vars.CC_DEPLOYMENT_NAME}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --output json | jq -r '.properties.outputs.webappName')
            SWA_CLI_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list --name $webappName --query "properties.apiKey")
            samples/apps/copilot-chat-app/deploy/deploy-webapp.ps1 --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --deployment-name ${{vars.CC_DEPLOYMENT_NAME}} --application-id ${{vars.APPLICATION_CLIENT_ID}}
