name: copilot-deploy-infra

on:
  workflow_call:
    inputs:
      AZUREOPENAI__NAME:
        required: true
        type: string
      AZUREOPENAI_DEPLOYMENT_GROUP_NAME:
        required: true
        type: string
      CC_DEPLOYMENT_GROUP_NAME:
        required: true
        type: string
      CC_DEPLOYMENT_NAME:
        required: true
        type: string
      CC_DEPLOYMENT_REGION:
        required: true
        type: string
      AZUREOPENAI_ENDPOINT:
        required: true
        type: string
      WEBAPP_API_SKU:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-infra:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false

      - name: deploy-infra
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            AI_SERVICE_KEY=$(az cognitiveservices account keys list --name ${{inputs.AZUREOPENAI__NAME}} --resource-group ${{inputs.AZUREOPENAI_DEPLOYMENT_GROUP_NAME}} | jq -r '.key1')
            samples/apps/copilot-chat-app/deploy/deploy-azure.sh --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --resource-group ${{inputs.CC_DEPLOYMENT_GROUP_NAME}} --deployment-name ${{inputs.CC_DEPLOYMENT_NAME}} --region ${{inputs.CC_DEPLOYMENT_REGION}} --ai-service AzureOpenAI --ai-endpoint ${{inputs.AZUREOPENAI_ENDPOINT}} --ai-service-key $AI_SERVICE_KEY --app-service-sku ${{inputs.WEBAPP_API_SKU}} --debug-deployment
