name: copilot-deploy-backend

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read

jobs:
  web-api:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.ARTIFACT_NAME}}
          path: webApiPackage

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false

      - name: deploy-infra
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            samples/apps/copilot-chat-app/deploy/deploy-webapi.sh --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --deployment-name ${{vars.CC_DEPLOYMENT_NAME}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --package webApiPackage/${{inputs.ARTIFACT_NAME}}/webapi.zip
